name: CI

on:
  push:
    branches: [main, setup-task]
  pull_request:
    branches: [main]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Recommended to update to v4

      - name: Set up Python 3.11 # Update description
        uses: actions/setup-python@v5 # Recommended to update to v5
        with:
          python-version: '3.11'
          cache: 'pip' # Highly recommended for faster builds

      - name: Install dependencies
        run: |
          python --version
          pip install -r requirements.txt